name: Test Simple Workflow kh

on: 
  push:
    branches:
      - main  # Vérifie que ta branche est bien "main"

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise Ubuntu comme environnement

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Afficher un message
        run: echo "Hello, GitHub Actions!"
